ALTER TABLE Sales ADD COLUMN Status INTEGER NOT NULL DEFAULT 2;
ALTER TABLE Sales ADD COLUMN PaidAt TEXT NULL;
ALTER TABLE Sales ADD COLUMN ReceivedAmount TEXT NULL;
ALTER TABLE Sales ADD COLUMN ChangeAmount TEXT NULL;
ALTER TABLE Sales ADD COLUMN OperationNumber TEXT NULL;
ALTER TABLE Sales ADD COLUMN IsVerified INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Sales ADD COLUMN CancelledAt TEXT NULL;
ALTER TABLE Sales ADD COLUMN CancelledReason TEXT NULL;

UPDATE Sales SET Status = 2 WHERE Status IS NULL OR Status = 0;
