CREATE TABLE IF NOT EXISTS Customers (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Dni TEXT NOT NULL,
    Name TEXT NULL,
    Phone TEXT NULL,
    Active INTEGER NOT NULL DEFAULT 1,
    CreatedAt TEXT NOT NULL,
    UpdatedAt TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS IX_Customers_Dni ON Customers(Dni);

ALTER TABLE Sales ADD COLUMN CustomerId INTEGER NULL;
CREATE INDEX IF NOT EXISTS IX_Sales_CustomerId ON Sales(CustomerId);
