CREATE TABLE IF NOT EXISTS Suppliers (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    TaxId TEXT NULL,
    Phone TEXT NULL,
    Address TEXT NULL,
    Active INTEGER NOT NULL DEFAULT 1,
    CreatedAt TEXT NOT NULL,
    UpdatedAt TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS IX_Suppliers_Name ON Suppliers(Name);

ALTER TABLE Products ADD COLUMN LastStockExchangeRateArs TEXT NOT NULL DEFAULT '0';
ALTER TABLE Sales ADD COLUMN GlobalDiscount TEXT NOT NULL DEFAULT '0';
